### ISSUE TITLE
Crash on High Sierra

### ISSUE THREAD

**Issue by WayneStewart** [miyako/4d-plugin-xslt#1]
G'day Keisuke,
After the upgrade to High Sierra the plugin now crashes :(
Thanks,
Wayne

**Comment by miyako** [comment]
Hello, 

thanks for reporting!

my upgrade to High Sierra ended up in a failure. I was forced to reinstall Sierra in recovery mode (``shift+command+R`` on reboot). a second OS update is ongoing but it remains to be seen if it turns out successful. then there is X code and all sorts of developer tools to compile and install.

**Comment by miyako** [comment]
seems related to dynamic linkage of ``libxml2`` and/or ``libxslt``. solved by static linkage.
